In [1]:
import numpy as np

# 1

In [2]:
n = 5
a = np.zeros((n*n))
for i in range(n-1):
    a[i*(n+1) + n] = i + 1
np.reshape(a,(n,n))

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

# 2

In [3]:
a = np.random.random((10,3))
np.min(np.abs(a - 0.5), 1)

array([0.30698792, 0.18858154, 0.02646985, 0.07906456, 0.13452011,
       0.27800069, 0.0427583 , 0.05108352, 0.21424003, 0.08714493])

# 3

In [4]:
a = np.random.random((6,6))
np.sum(a,1)/np.max(a,0)

array([6.7459925 , 3.37676083, 4.37262059, 3.01183833, 3.96365165,
       3.34756488])

# 4

In [5]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
tmp = np.array([], dtype=x.dtype)
for i in np.arange(len(x)):
    if(x[i] == 0):
       tmp = np.append(tmp, x[i-1])
np.max(tmp)

7

# 5

In [6]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for k in i:
    x[k] += 1
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

# 6

In [7]:
a = np.array([1, 0.6, 0.1, 2.5, -1.4, -5.9])
print(np.around(a),
     np.round(a),
      (a + ((a + 0.5) // 1) - (a // 1)) // 1, sep = '\n')

[ 1.  1.  0.  2. -1. -6.]
[ 1.  1.  0.  2. -1. -6.]
[ 1.  1.  0.  3. -1. -6.]


# 7

In [17]:
from sklearn.datasets import fetch_openml
from scipy.linalg import norm
import matplotlib.pyplot as plt
images, labels = fetch_openml('mnist_784', return_X_y=True, as_frame=False)

def pic(a):
    plt.imshow(a.reshape(28, 28), cmap='Greys_r')
    #plt.title('Number ' + labels[])
    plt.show()
def Norm(a):
    return norm(a,2)

def KNN(train_X, train_Y, test_X, k):
    result = np.array([])
    for i in range(test_size):
        Dist = np.fromiter(map(Norm, train_X - test_X[i]), float)
        #print(Dist)
        #print(np.argpartition(Dist, k)[:k])
        ind = np.argpartition(Dist, k)[:k]
        res = np.argmax(np.bincount(np.fromiter(map(int,train_labels[ind]), int)))
        result = np.append(result, res)
    return result    
# res = KNN(train_images, train_labels, test_images, 1)
# print(np.sum(res)/len(res))

# 8

In [33]:
train_size = 1000
test_size = 100
train_images = images[:train_size]
train_labels = labels[:train_size]
test_images = images[-test_size:]
test_labels = labels[-test_size:]
percentMax = 0
ind = 0
for i in range(1,10):
    res = KNN(train_images, train_labels, test_images, i)
    percent = np.sum(res == np.fromiter(map(int,test_labels), int)) / len(res)
    if(percent > percentMax):
        percentMax = percent
        ind = i
    print("Accuracy", percent*100, "% ", "for K =", i)
print("Best accuracy", percentMax*100, "% ", "for K =", ind)

Accuracy 94.0 %  for K = 1
Accuracy 91.0 %  for K = 2
Accuracy 90.0 %  for K = 3
Accuracy 90.0 %  for K = 4
Accuracy 89.0 %  for K = 5
Accuracy 86.0 %  for K = 6
Accuracy 87.0 %  for K = 7
Accuracy 87.0 %  for K = 8
Accuracy 86.0 %  for K = 9
Best accuracy 94.0 %  for K = 1
